install_data(
  'io.github.srwalkerb.DuckPackages.desktop',
  install_dir: get_option('datadir') / 'applications',
)
install_data(
  'io.github.srwalkerb.DuckPackages.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)
install_data(
  'icons/io.github.srwalkerb.DuckPackages.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps',
)
install_data(
  'icons/io.github.srwalkerb.DuckPackages-symbolic.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/symbolic/apps',
)
